yarnPath: .yarn/releases/yarn-3.5.0.cjs

# Turns on yarn zero-installs
enableGlobalCache: false

npmAuditRegistry: "https://registry.npmjs.org"

# Workaround for VE dependency on next internals :sad-panda:
# @see https://github.com/yarnpkg/berry/issues/587#issuecomment-605844400
nodeLinker: node-modules

# Cache dependencies for local + CI architectures
supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - glibc
  os:
    - current
    - darwin
    - linux
